name: nodejs Demo
on: workflow_dispatch
jobs:
  nodejs:
    runs-on: ubuntu-latest
    steps:
      - name: nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '16'
        run: node server.js
